name:                aws-dual-control
version:             0.1.0.0
github:              "githubuser/aws-dual-control"
license:             BSD3
author:              "Greg Wiley"
maintainer:          "aztex.rex@jammm.com"
copyright:           "2018 Greg Wiley"

extra-source-files:
- README.md

synopsis:            Multi-principal access control
category:            Operations

description:         See <https://github.com/aztecrex/aws-dual-control.git>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - amazonka
  - amazonka-core
  - amazonka-s3
  - amazonka-sqs
  - bytestring
  - data-default
  - freer-simple
  - hashable
  - lens
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src

tests:
  aws-dual-control-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aws-dual-control
    - tasty
    - tasty-hspec
    - tasty-hunit
    - hspec

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MonoLocalBinds
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies
